# Site settings
# title:
# email:
# description: > # this means to ignore newlines until "baseurl:"
# baseurl: "students-test/" # the subpath of your site, e.g. /blog/
# url: "" # the base hostname & protocol for your site

twitter_username: yourname
github_username: yourname
title: I.BA_222_GENCG.H1801
subtitle: I.BA_222_GENCG.H1801 - Winter 2018

# # Build settings
# markdown: kramdown

collections:
  01-Work-Process:
    output: true
    
  02-Final-Project:
    output: true